### ISSUE TITLE
NotFoundError: NewRandomAccessFile failed to Create/Open

### ISSUE THREAD

**Issue by PS061188** [HasnainRaz/Skin-Segmentation-TensorFlow#10]
NotFoundError: NewRandomAccessFile failed to Create/Open: C:/Users/HP/Desktop/.............\mask-newfamily-08.png : The system cannot find the file specified.
; No such file or directory
	 [[{{node ReadFile_1}}]]
	 [[{{node IteratorGetNext}}]]

I am getting this error fro every image in train and test folders while running the code. Even though the images are present on the mentioned path but unable to find the reason for the same.

**Comment by HasnainRaz** [comment]
Is that how the path really appears? with the '.....'. If so, then there could be a problem in the path to the directory containing the image.

Also, the code assumes that the folder for the images is present in the current working directory. If that's not the case, either move the folders to the directory where you execute the code from, or change the path construction logic in the main file.

**Comment by PS061188** [comment]
All the folders are present in the current working directory in which the code is present. I have tried these things but the error remain the same:
IMAGE_PATHS = 'C:/Users/HP/Desktop/Ph.D_Work/Dynamic_Gesture_Recognition/Work_on_Zafar_dataset/Codes/Dataset_Processing/Skin-Segmentation-TensorFlow-master/train'
MASK_PATHS = 'C:/Users/HP/Desktop/Ph.D_Work/Dynamic_Gesture_Recognition/Work_on_Zafar_dataset/Codes/Dataset_Processing/Skin-Segmentation-TensorFlow-master/val_train'
VAL_IMAGE_PATH = 'C:/Users/HP/Desktop/Ph.D_Work/Dynamic_Gesture_Recognition/Work_on_Zafar_dataset/Codes/Dataset_Processing/Skin-Segmentation-TensorFlow-master/test'
VAL_MASK_PATH = 'C:/Users/HP/Desktop/Ph.D_Work/Dynamic_Gesture_Recognition/Work_on_Zafar_dataset/Codes/Dataset_Processing/Skin-Segmentation-TensorFlow-master/val_test'
OUTPUT = 'C:/Users/HP/Desktop/Ph.D_Work/Dynamic_Gesture_Recognition/Work_on_Zafar_dataset/Codes/Dataset_Processing/Skin-Segmentation-TensorFlow-master/outputs'
MODEL = 'C:/Users/HP/Desktop/Ph.D_Work/Dynamic_Gesture_Recognition/Work_on_Zafar_dataset/Codes/Dataset_Processing/Skin-Segmentation-TensorFlow-master/model'

Also, this:
IMAGE_PATHS = 'train'
MASK_PATHS = 'val_train'
VAL_IMAGE_PATH = 'test'
VAL_MASK_PATH = 'val_test'
OUTPUT = 'outputs/'
MODEL = 'model/'

And this:
IMAGE_PATHS = 'train/'
MASK_PATHS = 'val_train/'
VAL_IMAGE_PATH = 'test/'
VAL_MASK_PATH = 'val_test/'
OUTPUT = 'outputs/'
MODEL = 'model/'

Full Error is:
Training inititated...
images_name_tensor =  Tensor("Const:0", shape=(57,), dtype=string)
mask_name_tensor =  Tensor("Const_1:0", shape=(57,), dtype=string)
image_content = Tensor("ReadFile:0", shape=(), dtype=string)
mask_content = Tensor("ReadFile_1:0", shape=(), dtype=string)
images = Tensor("DecodePng:0", shape=(?, ?, 3), dtype=uint8)
masks = Tensor("DecodePng_1:0", shape=(?, ?, 1), dtype=uint8)
data =  (<tf.Tensor 'IteratorGetNext:0' shape=(?, 480, 640, 3) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(?, 480, 640, 1) dtype=int32>)
images_name_tensor =  Tensor("Const_2:0", shape=(20,), dtype=string)
mask_name_tensor =  Tensor("Const_3:0", shape=(20,), dtype=string)
image_content = Tensor("ReadFile:0", shape=(), dtype=string)
mask_content = Tensor("ReadFile_1:0", shape=(), dtype=string)
images = Tensor("DecodePng:0", shape=(?, ?, 3), dtype=uint8)
masks = Tensor("DecodePng_1:0", shape=(?, ?, 1), dtype=uint8)
val_data = (<tf.Tensor 'IteratorGetNext_1:0' shape=(?, 480, 640, 3) dtype=float32>, <tf.Tensor 'IteratorGetNext_1:1' shape=(?, 480, 640, 1) dtype=int32>)
val_image_tensor = Tensor("IteratorGetNext_1:0", shape=(?, 480, 640, 3), dtype=float32)
val_mask_tensor = Tensor("IteratorGetNext_1:1", shape=(?, 480, 640, 1), dtype=int32)
Building Network for Inference...
Done, network built.
Training with learning rate:  0.0001
Step: 0
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\HP\Desktop\Ph.D_Work\Dynamic_Gesture_Recognition\Work_on_Zafar_dataset\Codes\Dataset_Processing\Skin-Segmentation-TensorFlow-master\val_train\mask-familyphoto07.png : The system cannot find the file specified.
; No such file or directory
	 [[{{node ReadFile_1}}]]
	 [[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-53-c57f0267bd92> in train(train_image_paths, train_mask_paths, val_image_path, val_mask_path, lr)
    150                         train_image, train_mask = sess.run(
--> 151                             [image_tensor, mask_tensor])
    152                         train_feed_dict = {

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 

NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\HP\Desktop\Ph.D_Work\Dynamic_Gesture_Recognition\Work_on_Zafar_dataset\Codes\Dataset_Processing\Skin-Segmentation-TensorFlow-master\val_train\mask-familyphoto07.png : The system cannot find the file specified.
; No such file or directory
	 [[{{node ReadFile_1}}]]
	 [[node IteratorGetNext (defined at <ipython-input-38-25a3a1375a3a>:180) ]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\HP\Desktop\Ph.D_Work\Dynamic_Gesture_Recognition\Work_on_Zafar_dataset\Codes\Dataset_Processing\Skin-Segmentation-TensorFlow-master\val_test\mask-amilyphoto.png : The system cannot find the file specified.
; No such file or directory
	 [[{{node ReadFile_1}}]]
	 [[{{node IteratorGetNext_1}}]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-53-c57f0267bd92> in <module>
    238     #infer(infer_paths)
    239     print('Training inititated...')
--> 240     train(image_paths, mask_paths, val_image_paths, val_mask_paths)

<ipython-input-53-c57f0267bd92> in train(train_image_paths, train_mask_paths, val_image_path, val_mask_path, lr)
    168                     val_iou, val_loss = 0, 0
    169                     val_image, val_mask = sess.run(
--> 170                         [val_image_tensor, val_mask_tensor])
    171                     val_feed_dict = {
    172                         image_placeholder: val_image,

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

~\Anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\HP\Desktop\Ph.D_Work\Dynamic_Gesture_Recognition\Work_on_Zafar_dataset\Codes\Dataset_Processing\Skin-Segmentation-TensorFlow-master\val_test\mask-amilyphoto.png : The system cannot find the file specified.
; No such file or directory
	 [[{{node ReadFile_1}}]]
	 [[node IteratorGetNext_1 (defined at <ipython-input-38-25a3a1375a3a>:180) ]]

**Comment by PS061188** [comment]
Any solution?

**Comment by HasnainRaz** [comment]
C:\Users\HP\Desktop\Ph.D_Work\Dynamic_Gesture_Recognition\Work_on_Zafar_dataset\Codes\Dataset_Processing\Skin-Segmentation-TensorFlow-master\val_test\mask-amilyphoto.png

Is this path correct? Seems like the f in family is missing? Also, are your images really png? Or are they in another format?

**Comment by PS061188** [comment]
While solving this problem, I realized that the names in the two folders: Pratheepan_Dataset and Ground_Truth are somewhat different like in one folder the name is familyphoto.png and in another folder the name is FamilyPhoto.png. So changed each name and made them the same. So this is the name of the image in both the folders - 'amilyphoto.png'. Thus, the name mismatch is not a problem. 

So what worked for me was to remove 'mask-' from these two lines in the main program:

mask_paths = [os.path.join(os.getcwd(), MASK_PATHS, 'mask-' + os.path.basename(x))
                  for x in image_paths]
val_mask_paths = [os.path.join(
        os.getcwd(), VAL_MASK_PATH, 'mask-' + os.path.basename(x)) for x in val_image_paths]
