### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by peterwilson3912** [HasnainRaz/Skin-Segmentation-TensorFlow#13]
Hi! Thank you so much for your amazing work. May I ask what kind of TensorFlow version are you using? I got so many errors from TensorFlow. Would you please double-check that? Thanks!

**Comment by HasnainRaz** [comment]
Hi, sadly this project is not maintained anymore. I don't exactly remember the tensorflow version, but I assume it was 1.14.
