### ISSUE TITLE
Is there any open source dataset of skin segmentation?

### ISSUE THREAD

**Issue by Mamba-ZJP** [HasnainRaz/Skin-Segmentation-TensorFlow#14]
Is there any open source dataset of skin segmentation? I am recently looking for them to finish a project.

**Comment by HasnainRaz** [comment]
Not many that I am aware of, but this seems useful: https://www.kaggle.com/competitions/cs4990-assignment-3-option-2-skin-segmentation/overview

**Comment by Mamba-ZJP** [comment]
I want to know that what skin dataset your model was trained on is.
