### ISSUE TITLE
train process is too slow 

### ISSUE THREAD

**Issue by vinnitu** [HasnainRaz/Skin-Segmentation-TensorFlow#5]
I don't know, maybe I do something wrong but I have GeForce GTX 1080 and see periodicaly used gpu, but not constantly usage and train process is too slow (ofcause with CPU it is tooo slow)

Can you share your results of training? how long does it take? What gpu you use?

**Comment by HasnainRaz** [comment]
GPU usage is dependent on the pipeline, you can increase gpu utilization by increasing the parameter in "prefetch(30)" in the input pipeline, and also by getting rid of the feed dict, and directly feeding in the queue to the network.
