### ISSUE TITLE
"InvalidArgumentError: assertion failed", any solution for this issue?

### ISSUE THREAD

**Issue by ghost** [HasnainRaz/Skin-Segmentation-TensorFlow#7]
...
line 1291, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: assertion failed: [Need value.shape >= size, got ] [640 427 3] [408 544 3]
	 [[Node: cond/random_crop/Assert/Assert = Assert[T=[DT_STRING, DT_INT32, DT_INT32], summarize=1000](cond/random_crop/All, cond/random_crop/Assert/Assert/data_0, cond/random_crop/Shape, cond/random_crop/size)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,480,640,3], [?,480,640,1]], output_types=[DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

**Comment by HasnainRaz** [comment]
Yeah, that's an issue with the crop size being larger than the image size, I don't know a good way of dynamically setting the crop size as a function of the current image size in tensorflow. You can simply comment out lines 150-151 in utility.py to get rid of random_crop to bypass this issue.

I'll try and come up with a fix soon.
